### ISSUE TITLE
Install Emacs fails with travis ci standard environment

### ISSUE THREAD

**Issue by marsam** [flycheck/emacs-travis#1]
Building Emacs in standard travis ci environment (`sudo: required`) fails, seem to be a problem with the build CFLAGS used

+ `.travis.yml`: https://github.com/marsam/melpa/blob/update-travis/.travis.yml)
+ travis build https://travis-ci.org/melpa/melpa/builds/110536199

**Comment by lunaryorn** [comment]
@marsam Uh, oh, I'm so sorry.  I totally overlooked this issue! 😞 😢 

Is the issue still relevant?  I'd presume that Travis' build environment has changed since, does it work now?

I took a look at the build error, but my C foo is too bad.  I can't make any sense of the error; maybe `-march=native` is the problem here?  

I don't think it's essential, shall I remove it?

**Comment by marsam** [comment]
Sorry for the late response. No worries :). I'm gonna test again in the in the next days and report back.

**Comment by lunaryorn** [comment]
@marsom Note that you can override `EMACSCONFFLAGS` to remove the `CFLAGS` setting to try and see if that fixes the breakage.

**Comment by marsam** [comment]
Sorry for the late response. I tried again in the standard environment and everything seems to work :) https://travis-ci.org/marsam/emacs-travis-test/
